site_name: Fizzysearch
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - navigation.top
    - header.autohide
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Introduction: index.md
  - Getting Started: start.md
  - Searching:
      - Fulltext: fts.md
      - RDF2vec: rdf2vec.md
      - Semantic: semantic.md
      - Images: imagesearch.md
  - Bloomtyper: bloomtyper.md
  - API Reference: api_reference.md
